language: python
python:
  - "3.8"
before_install:
  - cd nlp
install:
  - pip install -r requirements.txt
  - python -m spacy download en_core_web_sm
  - python -m spacy download en
  - python -m nltk.downloader "punkt"
  - python -m nltk.downloader "cmudict"
  - python -m nltk.downloader "wordnet"
before_script:
  - cp example.cfg project.cfg
script: 
  - python3 -m pytest tests/
cache: pip
notifications:
  slack:
    rooms:
      - hdap-team:kU41dKwGiEWGNRyHERIyMOFb#clarity-repo
